version: "3"
services:
  bot:
    container_name: my-discord-bot
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
  db:
    image: mysql:8.0
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: clandb
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${USER_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: